### PR TITLE
灰测报名

### LINKED ISSUE #1: 灰测报名
更新agile repo根目录下apply.md文件，参照第0位同学的方式标记你想加入的team。

### PR DESCRIPTION
**Pull request by bonnieyt**
Closes #1

Signed-off-by: Bonnie Young <bonnie.young@maxwit.com>

### CODE REVIEW

**Comment by bonnieyt** [comment]
@nsummer @lsp0525 @NicoleHuiLi  pls discuss with me

**Comment by lsp0525** [comment]
> @nsummer @lsp0525 @NicoleHuiLi pls discuss with me

收到

**Comment by nsummer** [comment]
好的呢

**Comment by nsummer** [comment]
> @nsummer @lsp0525 @NicoleHuiLi pls discuss with me

👌

**Pull request merged**
